### ISSUE TITLE
can't seem to get it working

### ISSUE THREAD

**Issue by kenkit** [Kaixhin/torch-pastalog#2]
can you add a simple example torch file?

**Comment by Kaixhin** [comment]
I just tried it and can confirm that this package is still working. Can you give me some more details? I have already provided an example [in the README](https://github.com/Kaixhin/torch-pastalog#usage). Torch needs a running pastalog server:
> See the pastalog installation instructions for details on how to set up and start the pastalog Node.js server. Once running:

If you can't get the pastalog server running such that you can see `http://localhost:8120/` in your browser, that is a pastalog issue.

**Comment by kenkit** [comment]
Okay 
I'm supposed to put 
```
local pastalog = require 'pastalog'

--[[
      Machine learning code
--]]

-- API is pastalog(modelName, seriesName, value, step, [url])
pastalog('model1', 'validLoss', 2.5, 1)
pastalog('model1', 'validLoss', 2.5, 1, 'http://localhost:8120/data')
```
In my `train.lua` then run `th train.lua` and open http://localhost:8120/data in my browser ?
Installed the luarocks package, do I  need to also install the pastalog server separately ?

**Comment by kenkit** [comment]
I tried doing the above but no Listening connection was opened

**Comment by Kaixhin** [comment]
Yes, you need to install **and** run the pastalog server separately. The instructions for that are [here on the pastalog readme](https://github.com/rewonc/pastalog#just-nodejs-server-useful-if-you-dont-want-the-python-api). If you can't install or run pastalog, you should find help on the pastalog repo.

**Comment by kenkit** [comment]
Okay thank you, but I wish you added a complete lua on the readme this stuff can be confusing at times.
